CREATE TABLE IF NOT EXISTS trips (
  uid TEXT PRIMARY KEY,
  username TEXT,
  origin_station TEXT,
  destination_station TEXT,
  start_datetime TEXT,
  end_datetime TEXT,
  estimated_trip_duration REAL,
  manual_trip_duration REAL,
  trip_length REAL,
  operator TEXT,
  countries TEXT,
  utc_start_datetime TEXT,
  utc_end_datetime TEXT,
  line_name TEXT,
  created TEXT,
  last_modified TEXT,
  type TEXT,
  material_type TEXT,
  seat TEXT,
  reg TEXT,
  waypoints TEXT,
  notes TEXT,
  price REAL,
  currency TEXT,
  purchasing_date TEXT,
  path TEXT,
  visibility TEXT,
  departure_delay REAL,
  arrival_delay REAL
)
